MachineLearning_WebApp_Ajax_ViewModels_FinalProject/Controllers/CommandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineLearning_WebApp_Ajax_ViewModels_FinalProject.Controllers;

[Authorize(Roles = "User, Administrator")]
public class CommandController : Controller
{
    public IActionResult CommandIndex() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandCreate() //done!
    {
        return View();
    }

    public IActionResult CommandDetails() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandEdit() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandDelete() //done!
    {
        return View();
    }
}

MachineLearning_WebApp_Ajax_ViewModels_FinalProject/Controllers/CommandSentenceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineLearning_WebApp_Ajax_ViewModels_FinalProject.Controllers;

[Authorize(Roles = "User, Administrator")]
public class CommandSentenceController : Controller
{
    public IActionResult CommandSentenceIndex() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandSentenceDetailedIndex() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandSentenceCreate() //done!
    {
        
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandSentenceDetails() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandSentenceEdit() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult CommandSentenceDelete() //done!
    {
        return View();
    }
}

MachineLearning_WebApp_Ajax_ViewModels_FinalProject/Controllers/SentenceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MachineLearning_WebApp_Ajax_ViewModels_FinalProject.Controllers;

[Authorize(Roles = "User, Administrator")]
public class SentenceController : Controller
{
    public IActionResult SentenceIndex() //done!
    {
        return View();
    }

    public IActionResult SentenceCreate() //done!
    {
        return View();
    }

    public IActionResult SentenceDetails() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult SentenceEdit() //done!
    {
        return View();
    }

    [Authorize(Roles = "Administrator")]
    public IActionResult SentenceDelete() //done!
    {
        return View();
    }
}

MachineLearning_WebApp_Ajax_ViewModels_FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MachineLearning_WebApp_Ajax_ViewModels_FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MachineLearning_WebApp_Ajax_ViewModels_FinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MachineLearning_WebApp_Ajax_ViewModels_FinalProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sentence" asp-action="SentenceIndex">| Sentence Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Command" asp-action="CommandIndex">Command Index</a> 
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CommandSentence" asp-action="CommandSentenceIndex">CommandSentence Index |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MachineLearning_WebApp_Ajax_ViewModels_FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>